default: &default
  docker:
  - image: choerodon/cibase:0.6.0

version: 2
jobs:
  maven_test_build:
      <<: *default

      working_directory: ~/repo
      environment:
        MAVEN_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
        - run: mvn package -U -DskipTests=false

  maven_build:
    <<: *default

    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn package -U -DskipTests=false
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target/app.jar

  docker_build:
    <<: *default
    steps:
      - setup_remote_docker:
            version: 17.05.0-ce
      - checkout
      - attach_workspace:
          at: .
      - run: |
          cp target/app.jar src/main/docker/app.jar
          sed -i "s/registry.cn-hangzhou.aliyuncs.com\/choerodon-tools/choerodon/g" src/main/docker/Dockerfile
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build --pull -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG} src/main/docker
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

  helm_chart_build:
    <<: *default
    steps:
      - checkout
      - run: |
          CHART_PATH=`find . -name Chart.yaml`
          yq w -i ${CHART_PATH%/*}/values.yaml image.repository ${DOCKER_GROUP_NAME}/${PROJECT_NAME}
          yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CIRCLE_TAG}
          helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
          helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CIRCLE_TAG} choerodon

workflows:
  version: 2
  release:
    jobs:
      - maven_build:
          context: org-global
          filters:
            tags:
              only: /^.*/
      - docker_build:
          context: org-global
          requires:
          - maven_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^hotfix-.*$/
                - /^release-.*$/
      - helm_chart_build:
          context: org-global
          requires:
          - maven_build
          - docker_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^hotfix-.*$/
                - /^release-.*$/
  general:
    jobs:
      - maven_test_build:
          context: org-global
          filters:
            branches:
              only:
                - /^.*/